// Ingredient catalog + starting price catalog.
// Single source of truth: used by tests and compiled into supabase/seed.sql by scripts/build-seed.ts.
// Prices are ESTIMATES (manually_verified_at = null). The app shows them as unverified until the
// family confirms or corrects them in "Настройки семьи → Цены".
import type { Ingredient, IngredientPrice, Unit } from "../functions/_shared/planner/types.ts";

type Row = [
  id: string,
  name: string,
  category: string,
  unit: Unit,
  kcal: number | null,
  tags: string[],
  aliases: string[],
  gramsPerPiece?: number,
];

const rows: Row[] = [
  ["chicken_breast", "куриная грудка", "meat", "g", 113, ["poultry", "chicken"], ["филе куриное", "куриное филе", "грудка куриная", "курица грудка", "филе грудки", "куринная грудка"]],
  ["chicken_mince", "куриный фарш", "meat", "g", 143, ["poultry", "chicken", "mince"], ["фарш куриный"]],
  ["beef", "говядина", "meat", "g", 187, ["beef"], ["говядина мякоть", "мякоть говядины", "говяжья вырезка"]],
  ["beef_mince", "говяжий фарш", "meat", "g", 254, ["beef", "mince"], ["фарш говяжий", "фарш из говядины"]],
  ["chebupeli", "чебупели с говядиной", "convenience", "g", 260, ["convenience", "beef", "semi_finished"], ["чебупели"]],
  ["pork", "свинина", "meat", "g", 259, ["pork"], ["свиная шея", "свиной фарш", "бекон", "ветчина"]],
  ["turkey", "индейка", "meat", "g", 150, ["poultry", "turkey"], ["филе индейки"]],
  ["chicken_thigh", "куриное бедро", "meat", "g", 185, ["poultry", "chicken"], ["бедро куриное", "куриные бёдра", "окорочок"]],
  ["salmon", "лосось", "fish", "g", 208, ["fish"], ["семга", "сёмга", "форель"]],
  ["white_fish", "белая рыба", "fish", "g", 80, ["fish"], ["минтай", "треска", "хек"]],
  ["orange", "апельсин", "fruit", "pcs", 43, ["fruit", "citrus", "orange"], ["апельсины"], 200],
  ["peanut_butter", "арахисовая паста", "spread", "g", 588, ["peanut"], ["арахисовое масло"]],
  ["hummus", "хумус", "spread", "g", 166, ["hummus"], []],
  ["rice_brown", "коричневый рис", "grain", "g", 337, ["rice", "brown_rice"], ["бурый рис", "рис бурый", "рис коричневый"]],
  ["mushrooms", "шампиньоны", "vegetable", "g", 27, ["mushroom"], ["грибы", "шампиньон"]],
  ["lime", "лайм", "fruit", "pcs", 30, ["fruit", "citrus"], ["лаймы"], 60],
  ["egg_noodles", "яичная лапша", "grain", "g", 350, ["pasta", "noodles"], ["лапша"]],
  ["rice_white", "рис белый", "grain", "g", 344, ["rice"], ["рис", "белый рис", "рис круглозерный", "рис длиннозерный", "рис басмати", "рис жасмин"]],
  ["pasta", "макароны", "grain", "g", 350, ["pasta"], ["паста", "спагетти", "пенне", "фузилли", "макаронные изделия"]],
  ["buckwheat", "гречка", "grain", "g", 313, ["buckwheat"], ["гречневая крупа", "крупа гречневая"]],
  ["bulgur", "булгур", "grain", "g", 342, ["bulgur"], []],
  ["oats", "овсяные хлопья", "grain", "g", 352, ["oats"], ["овсянка", "геркулес", "хлопья овсяные"]],
  ["semolina", "манная крупа", "grain", "g", 333, ["semolina"], ["манка"]],
  ["flour", "мука пшеничная", "grain", "g", 334, ["flour"], ["мука"]],
  ["bread", "хлеб", "bakery", "g", 250, ["bread"], ["хлеб белый", "батон", "хлеб для тостов", "тостовый хлеб"]],
  ["tortilla", "тортилья", "bakery", "pcs", 300, ["bread"], ["тортильи", "лепешка тортилья", "пшеничная лепешка"], 40],
  ["crispbread", "хлебцы", "bakery", "g", 360, ["bread"], ["хлебцы ржаные"]],
  ["granola", "гранола", "grain", "g", 420, ["sweet"], ["мюсли"]],
  ["potato", "картофель", "vegetable", "g", 77, ["potato", "starchy"], ["картошка", "картофель молодой"]],
  ["zucchini", "кабачок", "vegetable", "g", 24, ["zucchini"], ["кабачки", "цукини"]],
  ["cucumber", "огурец", "vegetable", "g", 15, ["fresh_veg"], ["огурцы"]],
  ["tomato", "помидор", "vegetable", "g", 20, ["fresh_veg"], ["помидоры", "томат", "томаты", "черри"]],
  ["bell_pepper", "перец болгарский", "vegetable", "g", 26, ["fresh_veg"], ["болгарский перец", "перец сладкий"]],
  ["onion", "лук репчатый", "vegetable", "g", 41, ["aromatic"], ["лук", "луковица"]],
  ["carrot", "морковь", "vegetable", "g", 35, ["root"], ["морковка"]],
  ["garlic", "чеснок", "vegetable", "g", 143, ["aromatic"], ["чеснока"]],
  ["beet", "свекла", "vegetable", "g", 43, ["root"], ["свёкла", "буряк"]],
  ["cabbage", "капуста белокочанная", "vegetable", "g", 28, ["cabbage"], ["капуста"]],
  ["broccoli", "брокколи замороженная", "vegetable", "g", 28, ["frozen_veg"], ["брокколи"]],
  ["greens", "зелень", "vegetable", "g", 40, ["greens"], ["укроп", "петрушка", "зеленый лук"]],
  ["apple", "яблоко", "fruit", "pcs", 47, ["fruit", "apple"], ["яблоки"], 170],
  ["banana", "банан", "fruit", "pcs", 96, ["fruit", "banana"], ["бананы"], 120],
  ["pear", "груша", "fruit", "pcs", 47, ["fruit", "pear"], ["груши"], 170],
  ["berries_frozen", "ягоды замороженные", "fruit", "g", 45, ["berries"], ["ягоды", "ягодная смесь", "черника", "малина"]],
  ["prunes", "чернослив", "fruit", "g", 256, ["dried_fruit"], []],
  ["cottage_cheese", "творог 5%", "dairy", "g", 121, ["cottage_cheese"], ["творог"]],
  ["sour_cream", "сметана 15%", "dairy", "g", 162, ["dairy_fat"], ["сметана"]],
  ["cream", "сливки 10%", "dairy", "ml", 119, ["dairy_fat", "liquid"], ["сливки"]],
  ["milk", "молоко 2,5%", "dairy", "ml", 52, ["liquid"], ["молоко"]],
  ["kefir", "кефир 1%", "dairy", "ml", 40, ["liquid"], ["кефир"]],
  ["ryazhenka", "ряженка 2,5%", "dairy", "ml", 54, ["liquid"], ["ряженка"]],
  ["yogurt", "йогурт натуральный", "dairy", "g", 68, ["yogurt"], ["йогурт", "греческий йогурт"]],
  ["cheese", "сыр полутвёрдый", "dairy", "g", 350, ["cheese"], ["сыр", "сыр российский", "сыр гауда", "моцарелла"]],
  ["butter", "масло сливочное", "fat", "g", 748, ["fat"], ["сливочное масло"]],
  ["egg", "яйцо куриное", "egg", "pcs", 157, ["egg"], ["яйца", "яйцо"], 55],
  ["oil", "масло подсолнечное", "fat", "ml", 899, ["fat", "liquid"], ["растительное масло", "подсолнечное масло", "масло растительное"]],
  ["soy_sauce", "соевый соус", "sauce", "ml", 55, ["sauce", "salty", "liquid"], ["соус соевый"]],
  ["teriyaki", "соус терияки", "sauce", "ml", 90, ["sauce", "salty", "liquid"], ["терияки"]],
  ["tomato_paste", "томатная паста", "sauce", "g", 102, ["sauce"], []],
  ["tomatoes_canned", "томаты в собственном соку", "sauce", "g", 24, ["sauce"], ["томаты консервированные", "пассата", "протертые томаты"]],
  ["honey", "мёд", "sweet", "g", 304, ["sweet"], ["мед"]],
  ["sugar", "сахар", "sweet", "g", 398, ["sweet"], []],
  ["walnuts", "грецкие орехи", "nuts", "g", 654, ["nuts"], ["орехи грецкие"]],
];

export const INGREDIENTS: Ingredient[] = rows.map(([id, name, category, unit, kcal, tags, aliases, gpp]) => ({
  id,
  canonical_name: name,
  category,
  default_unit: unit,
  kcal_per_100g: kcal,
  tags,
  aliases,
  grams_per_piece: gpp ?? null,
  active: true,
}));

type P = [string, string, number, number, Unit];
const PY = "Пятёрочка", CH = "Чижик", VV = "ВкусВилл";
const priceRows: P[] = [
  ["chicken_breast", PY, 399, 900, "g"], ["chicken_breast", CH, 349, 900, "g"], ["chicken_breast", VV, 469, 800, "g"],
  ["chicken_mince", PY, 229, 400, "g"], ["chicken_mince", CH, 199, 400, "g"],
  ["beef", PY, 429, 500, "g"], ["beef", CH, 389, 500, "g"], ["beef", VV, 499, 400, "g"],
  ["beef_mince", PY, 299, 400, "g"], ["beef_mince", CH, 269, 400, "g"],
  ["chebupeli", PY, 189, 300, "g"], ["chebupeli", CH, 169, 300, "g"],
  ["rice_white", PY, 119, 900, "g"], ["rice_white", CH, 99, 900, "g"],
  ["pasta", PY, 89, 450, "g"], ["pasta", CH, 69, 450, "g"],
  ["buckwheat", PY, 99, 800, "g"], ["buckwheat", CH, 85, 800, "g"],
  ["bulgur", PY, 109, 500, "g"], ["bulgur", VV, 139, 500, "g"],
  ["oats", PY, 79, 500, "g"], ["oats", CH, 65, 500, "g"],
  ["semolina", PY, 69, 700, "g"], ["semolina", CH, 59, 700, "g"],
  ["flour", PY, 79, 1000, "g"], ["flour", CH, 65, 1000, "g"],
  ["bread", PY, 65, 400, "g"], ["bread", CH, 55, 400, "g"],
  ["tortilla", PY, 139, 6, "pcs"], ["tortilla", CH, 119, 6, "pcs"],
  ["crispbread", PY, 89, 150, "g"], ["crispbread", VV, 119, 150, "g"],
  ["granola", PY, 199, 300, "g"], ["granola", VV, 249, 300, "g"],
  ["potato", PY, 59, 1500, "g"], ["potato", CH, 45, 1500, "g"],
  ["zucchini", PY, 139, 1000, "g"], ["zucchini", CH, 119, 1000, "g"],
  ["cucumber", PY, 169, 1000, "g"], ["cucumber", CH, 149, 1000, "g"],
  ["tomato", PY, 229, 1000, "g"], ["tomato", CH, 199, 1000, "g"],
  ["bell_pepper", PY, 299, 1000, "g"], ["bell_pepper", CH, 269, 1000, "g"],
  ["onion", PY, 45, 1000, "g"], ["onion", CH, 39, 1000, "g"],
  ["carrot", PY, 49, 1000, "g"], ["carrot", CH, 42, 1000, "g"],
  ["garlic", PY, 49, 100, "g"], ["garlic", CH, 39, 100, "g"],
  ["beet", PY, 45, 1000, "g"], ["beet", CH, 39, 1000, "g"],
  ["cabbage", PY, 35, 1000, "g"], ["cabbage", CH, 29, 1000, "g"],
  ["broccoli", PY, 189, 400, "g"], ["broccoli", CH, 159, 400, "g"],
  ["greens", PY, 59, 50, "g"], ["greens", CH, 49, 50, "g"],
  ["apple", PY, 139, 1000, "g"], ["apple", CH, 119, 1000, "g"],
  ["banana", PY, 149, 1000, "g"], ["banana", CH, 129, 1000, "g"],
  ["pear", PY, 229, 1000, "g"], ["pear", CH, 199, 1000, "g"],
  ["berries_frozen", PY, 249, 300, "g"], ["berries_frozen", CH, 199, 300, "g"],
  ["prunes", PY, 159, 200, "g"],
  ["cottage_cheese", PY, 149, 350, "g"], ["cottage_cheese", CH, 129, 350, "g"], ["cottage_cheese", VV, 179, 300, "g"],
  ["sour_cream", PY, 109, 300, "g"], ["sour_cream", CH, 95, 300, "g"],
  ["cream", PY, 119, 500, "ml"], ["cream", CH, 99, 500, "ml"],
  ["milk", PY, 89, 900, "ml"], ["milk", CH, 79, 900, "ml"],
  ["kefir", PY, 89, 900, "ml"], ["kefir", CH, 79, 900, "ml"],
  ["ryazhenka", PY, 99, 900, "ml"], ["ryazhenka", VV, 119, 900, "ml"],
  ["yogurt", PY, 89, 350, "g"], ["yogurt", VV, 119, 400, "g"],
  ["cheese", PY, 229, 250, "g"], ["cheese", CH, 199, 250, "g"],
  ["butter", PY, 189, 180, "g"], ["butter", CH, 169, 180, "g"],
  ["egg", PY, 119, 10, "pcs"], ["egg", CH, 99, 10, "pcs"],
  ["oil", PY, 139, 1000, "ml"], ["oil", CH, 119, 1000, "ml"],
  ["soy_sauce", PY, 119, 300, "ml"], ["soy_sauce", CH, 99, 300, "ml"],
  ["teriyaki", PY, 169, 250, "ml"],
  ["tomato_paste", PY, 79, 270, "g"], ["tomato_paste", CH, 65, 270, "g"],
  ["tomatoes_canned", PY, 139, 400, "g"], ["tomatoes_canned", VV, 179, 500, "g"],
  ["honey", PY, 299, 250, "g"], ["honey", CH, 249, 250, "g"],
  ["sugar", PY, 89, 1000, "g"], ["sugar", CH, 75, 1000, "g"],
  ["walnuts", PY, 199, 100, "g"],
];

export const PRICES: IngredientPrice[] = priceRows.map(([ingredient_id, store, price_rub, package_amount, package_unit]) => ({
  ingredient_id,
  store,
  price_rub,
  package_amount,
  package_unit,
  manually_verified_at: null,
}));
