import type { Recipe } from "../functions/_shared/planner/types.ts";
export const RECIPES_4: Recipe[] = [
{"id":"rice_milk_porridge","title":"Рисовая каша на молоке с маслом","meal_types":["breakfast"],"tags":["porridge","sweet"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":["stove","pot","multicooker"],"cook_minutes":30,"ref_portion_g":280,"ingredients":[{"ingredient_id":"rice_white","amount":40,"state":"dry"},{"ingredient_id":"milk","amount":200,"state":"raw"},{"ingredient_id":"butter","amount":5,"state":"raw"},{"ingredient_id":"sugar","amount":5,"state":"raw"}],"steps":["Рис промыть, отварить в 100 мл воды 7 минут.","Влить молоко, варить на слабом огне 15 минут, помешивая (или режим «Молочная каша»).","Добавить масло и сахар."],"child_adaptation":"Та же каша, чуть жиже.","seasoning":"Щепотка соли.","child_ok":true},
{"id":"hot_toasts_cheese_tomato","title":"Горячие тосты с сыром и помидором, кефир","meal_types":["breakfast"],"tags":["savory"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":["toaster","electric_grill"],"cook_minutes":10,"ref_portion_g":230,"ingredients":[{"ingredient_id":"bread","amount":65,"state":"raw"},{"ingredient_id":"cheese","amount":25,"state":"raw"},{"ingredient_id":"tomato","amount":50,"state":"raw"},{"ingredient_id":"butter","amount":4,"state":"raw"},{"ingredient_id":"kefir","amount":100,"state":"raw"}],"steps":["Хлеб подсушить в тостере.","Выложить помидор и сыр, прогреть на электрогриле под крышкой 2 минуты до расплавления.","Подать со стаканом кефира."],"child_adaptation":"Половинка тоста, нарезанная полосками.","seasoning":"Без дополнительной соли.","child_ok":true},
{"id":"yogurt_granola_banana","title":"Йогурт с гранолой и бананом","meal_types":["breakfast"],"tags":["sweet","no_cook"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":3,"ref_portion_g":250,"ingredients":[{"ingredient_id":"yogurt","amount":170,"state":"raw"},{"ingredient_id":"granola","amount":35,"state":"dry"},{"ingredient_id":"banana","amount":0.5,"state":"raw"}],"steps":["Выложить йогурт, сверху гранолу и нарезанный банан."],"child_adaptation":"Гранолу размочить в йогурте 5 минут.","seasoning":"—","child_ok":true},
{"id":"semolina_porridge","title":"Манная каша с ягодами","meal_types":["breakfast"],"tags":["porridge","sweet"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":["stove","pot"],"cook_minutes":10,"ref_portion_g":260,"ingredients":[{"ingredient_id":"semolina","amount":30,"state":"dry"},{"ingredient_id":"milk","amount":200,"state":"raw"},{"ingredient_id":"butter","amount":4,"state":"raw"},{"ingredient_id":"sugar","amount":5,"state":"raw"},{"ingredient_id":"berries_frozen","amount":30,"state":"frozen"}],"steps":["Молоко довести до кипения, тонкой струйкой всыпать манку, помешивая.","Варить 3 минуты.","Добавить масло, сахар, ягоды."],"child_adaptation":"Та же каша.","seasoning":"Щепотка соли.","child_ok":true},
{"id":"snack_apple","title":"Яблоко","meal_types":["snack1","snack2"],"tags":["fruit","apple"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":170,"ingredients":[{"ingredient_id":"apple","amount":1,"state":"raw"}],"steps":["Вымыть, нарезать дольками."],"child_adaptation":"Тонкие дольки без кожуры.","seasoning":"—","child_ok":true},
{"id":"snack_banana","title":"Банан","meal_types":["snack1","snack2"],"tags":["fruit","banana"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":120,"ingredients":[{"ingredient_id":"banana","amount":1,"state":"raw"}],"steps":["Очистить."],"child_adaptation":"Половина банана.","seasoning":"—","child_ok":true},
{"id":"snack_pear","title":"Груша","meal_types":["snack1","snack2"],"tags":["fruit","pear"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":170,"ingredients":[{"ingredient_id":"pear","amount":1,"state":"raw"}],"steps":["Вымыть, нарезать."],"child_adaptation":"Мягкие дольки без кожуры.","seasoning":"—","child_ok":true}
];