import type { Recipe } from "../functions/_shared/planner/types.ts";
export const RECIPES_5: Recipe[] = [
{"id":"snack_kefir","title":"Кефир","meal_types":["snack1","snack2"],"tags":["dairy"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":250,"ingredients":[{"ingredient_id":"kefir","amount":250,"state":"raw"}],"steps":["Налить стакан."],"child_adaptation":"Полстакана.","seasoning":"—","child_ok":true},
{"id":"snack_ryazhenka","title":"Ряженка","meal_types":["snack1","snack2"],"tags":["dairy"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":250,"ingredients":[{"ingredient_id":"ryazhenka","amount":250,"state":"raw"}],"steps":["Налить стакан."],"child_adaptation":"Полстакана.","seasoning":"—","child_ok":true},
{"id":"snack_yogurt_berries","title":"Натуральный йогурт с ягодами","meal_types":["snack1","snack2"],"tags":["dairy"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":2,"ref_portion_g":180,"ingredients":[{"ingredient_id":"yogurt","amount":150,"state":"raw"},{"ingredient_id":"berries_frozen","amount":30,"state":"frozen"}],"steps":["Разморозить ягоды, смешать с йогуртом."],"child_adaptation":"Половина порции.","seasoning":"—","child_ok":true},
{"id":"snack_cottage_honey","title":"Творог с мёдом","meal_types":["snack1","snack2"],"tags":["dairy","cottage_cheese"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":1,"ref_portion_g":110,"ingredients":[{"ingredient_id":"cottage_cheese","amount":100,"state":"raw"},{"ingredient_id":"honey","amount":8,"state":"raw"}],"steps":["Выложить творог, полить мёдом."],"child_adaptation":"Без мёда, с размятой ягодой.","seasoning":"—","child_ok":true},
{"id":"snack_crispbread_cheese","title":"Хлебцы с сыром и огурцом","meal_types":["snack1","snack2"],"tags":["savory"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":2,"ref_portion_g":90,"ingredients":[{"ingredient_id":"crispbread","amount":20,"state":"raw"},{"ingredient_id":"cheese","amount":20,"state":"raw"},{"ingredient_id":"cucumber","amount":50,"state":"raw"}],"steps":["Выложить сыр и огурец на хлебцы."],"child_adaptation":"Сыр кусочками, огурец брусочками.","seasoning":"—","child_ok":true},
{"id":"snack_carrot_yogurt_dip","title":"Морковные палочки с йогуртовым соусом","meal_types":["snack1","snack2"],"tags":["vegetable"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":5,"ref_portion_g":160,"ingredients":[{"ingredient_id":"carrot","amount":100,"state":"raw"},{"ingredient_id":"yogurt","amount":60,"state":"raw"},{"ingredient_id":"greens","amount":2,"state":"raw"}],"steps":["Морковь нарезать палочками.","Йогурт смешать с зеленью и щепоткой соли."],"child_adaptation":"Морковь натереть или отварить до мягкости.","seasoning":"Щепотка соли в соус.","child_ok":true},
{"id":"snack_walnuts_prunes","title":"Грецкие орехи и чернослив","meal_types":["snack1","snack2"],"tags":["nuts"],"side":null,"active":true,"batchable":false,"batch_days":1,"equipment":[],"cook_minutes":0,"ref_portion_g":40,"ingredients":[{"ingredient_id":"walnuts","amount":20,"state":"raw"},{"ingredient_id":"prunes","amount":20,"state":"dry"}],"steps":["Отмерить горсть."],"child_adaptation":"Ребёнку 2 лет цельные орехи не давать — только чернослив, мелко нарезанный.","seasoning":"—","child_ok":false}
];