// Generates supabase/seed.sql from the TypeScript catalog (single source of truth).
// Usage: node --experimental-strip-types scripts/build-seed.ts   (CI fails if the committed file is stale)
import { writeFileSync } from "node:fs";
import { INGREDIENTS, PRICES } from "../supabase/seed/ingredients.ts";
import { RECIPES } from "../supabase/seed/recipes.ts";
import { DEFAULT_CAPS, DEFAULT_RULES, DEFAULT_SETTINGS } from "../supabase/seed/family_defaults.ts";
import { normalizeName } from "../supabase/functions/_shared/planner/normalize.ts";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replaceAll("'", "''")}'`;
};
const arr = (a: string[]) => `array[${a.map(q).join(",")}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  "-- GENERATED by scripts/build-seed.ts — do not edit by hand.",
  "-- Idempotent: catalog rows are upserted; family data is only initialised when missing.",
  "begin;",
];

for (const i of INGREDIENTS) {
  out.push(`insert into public.ingredient_catalog (id, canonical_name, category, tags, default_unit, grams_per_piece, kcal_per_100g, active) values (${q(i.id)}, ${q(i.canonical_name)}, ${q(i.category)}, ${arr(i.tags)}, ${q(i.default_unit)}, ${q(i.grams_per_piece)}, ${q(i.kcal_per_100g)}, ${q(i.active)}) on conflict (id) do update set canonical_name = excluded.canonical_name, category = excluded.category, tags = excluded.tags, default_unit = excluded.default_unit, grams_per_piece = excluded.grams_per_piece, kcal_per_100g = excluded.kcal_per_100g, updated_at = now();`);
  for (const a of new Set([i.canonical_name, ...i.aliases].map(normalizeName))) {
    out.push(`insert into public.ingredient_aliases (alias_norm, ingredient_id) values (${q(a)}, ${q(i.id)}) on conflict (alias_norm) do update set ingredient_id = excluded.ingredient_id;`);
  }
}
for (const p of PRICES) {
  out.push(`insert into public.ingredient_prices (ingredient_id, store, price_rub, package_amount, package_unit, effective_from, manually_verified_at) values (${q(p.ingredient_id)}, ${q(p.store)}, ${q(p.price_rub)}, ${q(p.package_amount)}, ${q(p.package_unit)}, date '2026-09-28', null) on conflict (ingredient_id, store, effective_from) do nothing;`);
}
for (const r of RECIPES) {
  out.push(`insert into public.recipes (id, title, meal_types, tags, side, active, batchable, batch_days, equipment, cook_minutes, ref_portion_g, steps, child_adaptation, seasoning, child_ok) values (${q(r.id)}, ${q(r.title)}, ${arr(r.meal_types)}, ${arr(r.tags)}, ${q(r.side ?? null)}, ${q(r.active)}, ${q(r.batchable)}, ${q(r.batch_days)}, ${arr(r.equipment)}, ${q(r.cook_minutes)}, ${q(r.ref_portion_g)}, ${json(r.steps)}, ${q(r.child_adaptation)}, ${q(r.seasoning)}, ${q(r.child_ok)}) on conflict (id) do update set title = excluded.title, meal_types = excluded.meal_types, tags = excluded.tags, side = excluded.side, batchable = excluded.batchable, batch_days = excluded.batch_days, equipment = excluded.equipment, cook_minutes = excluded.cook_minutes, ref_portion_g = excluded.ref_portion_g, steps = excluded.steps, child_adaptation = excluded.child_adaptation, seasoning = excluded.seasoning, child_ok = excluded.child_ok, updated_at = now();`);
  out.push(`delete from public.recipe_ingredients where recipe_id = ${q(r.id)};`);
  r.ingredients.forEach((ri, pos) => {
    out.push(`insert into public.recipe_ingredients (recipe_id, ingredient_id, amount, state, optional, position) values (${q(r.id)}, ${q(ri.ingredient_id)}, ${q(ri.amount)}, ${q(ri.state)}, ${q(!!ri.optional)}, ${pos});`);
  });
}

// Initialise defaults for every existing family that has none yet (never overwrites user edits).
out.push(`insert into public.family_settings (family_id, settings) select f.id, ${json(DEFAULT_SETTINGS)} from public.families f on conflict (family_id) do nothing;`);
for (const c of DEFAULT_CAPS) {
  const conflict = c.ingredient_id ? "(family_id, ingredient_id) where ingredient_id is not null" : "(family_id, category) where category is not null";
  out.push(`insert into public.family_ingredient_caps (family_id, ingredient_id, category, max_amount, unit, enabled) select f.id, ${q(c.ingredient_id ?? null)}, ${q(c.category ?? null)}, ${q(c.max_amount)}, ${q(c.unit)}, ${q(c.enabled)} from public.families f on conflict ${conflict} do nothing;`);
}
for (const r of DEFAULT_RULES) {
  out.push(`insert into public.family_rules (family_id, rule_type, description, enabled, rule_kind, params) select f.id, ${q(r.rule_type)}, ${q(r.description)}, true, ${q(r.rule.kind)}, ${json(r.rule)} from public.families f where not exists (select 1 from public.family_rules x where x.family_id = f.id and x.params = ${json(r.rule)});`);
}
out.push("commit;", "");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(`seed.sql: ${INGREDIENTS.length} ingredients, ${PRICES.length} prices, ${RECIPES.length} recipes`);
